import Head from 'next/head'
import { Container, Main, Title } from '../styles/sharedstyles'
import { Cards } from '../components'

export default function Home() {
	return (
		<Container>
			<Head>
				<title>Wedding Website</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Main>
				<Title>Wedding Website</Title>
				<Cards />
			</Main>
		</Container>
	)
}
