import Head from 'next/head'
import { Container, Main, Title } from '../styles/sharedstyles'
import content from '../../content/homepage/index.json'
import ComponentLoader from '@/components/ComponentLoader'

export default function Home() {
	const { title, sections, fianceId } = content
	return (
		<Container>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Main>
				<Title>{title}</Title>
				{sections.map((section) => (
					<ComponentLoader fianceId={fianceId} {...section} />
				))}
			</Main>
		</Container>
	)
}
